---
- name: "git | paquetes instalados"
  become: true
  apt:
    pkg:
      - git
- name: "git | editor configurado"
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  loop:
    - name:  core.editor
      value: "vim -n +1"
    - name:  push.default
      value: simple
    - name:  pull.ff
      value: only
    - name:  color.ui
      value: "true"
    - name:  user.name
      value: "{{ target_user_name }}"
    - name:  user.email
      value: "{{ target_user_email }}"
  loop_control:
    label: "{{ item.name }}"
