---
- name: "lightdm | background"
  become: true
  community.general.ini_file:
    path: /etc/lightdm/lightdm-gtk-greeter.conf
    section: "greeter"
    option: "background"
    # TODO: este archivo está en un paquete en la vuelta
    value: "/usr/share/backgrounds/pexels-scott-webb-1931143.jpg"
