# TODO:
# - name: Fuentes configuradas
#   become: true
#   template:
#     src: 'sources.list'
#     dest: '/etc/apt/sources.list'
#   register: config
#   when: ansible_distribution == 'Debian'

---
- name: Paquetes instalados
  become: true
  apt:
    pkg:
      - golang # esto no siempre se necesita
      - jq
- name: Paquetes extra instalados
  become: true
  apt:
    pkg:
      # Visor de imágenes
      - viewnior
      - syncthing-gtk
      - keepassxc
      - xfce4-whiskermenu-plugin
      - syncthing
  when: not workstation_headless

# TODO: rename all to .yaml
- include: updates.yaml
- include: xdg.yml
- include: git.yml
- include: ssh.yml
- include: dotfiles.yml
- include: vim.yml
- include: tmux.yml
- include: ipod.yml
  when: workstation_use_ipod
- include: flatpak.yml
  when: workstation_use_flatpak
- include: redshift.yaml
  when: not workstation_headless
- include: keyboard.yaml
  when: not workstation_headless
