---
- hosts: k3s_nodes
  roles:
    - k3s-ansible/roles/prereq
    - k3s-ansible/roles/download

- hosts: k3s_pi
  roles:
    - k3s-ansible/roles/raspberrypi

- hosts: k3s_nodes
  become: true
  tasks:
    - apt:
        name:
          - open-iscsi # Para longhorn
          - nfs-common # Para nfs

- hosts: k3s_server[0]
  roles:
    - k3s-ansible/roles/k3s/server
    - k3s-access

- hosts: k3s_agents
  roles:
    - k3s-ansible/roles/k3s/agent

- hosts: k3s_server[1:]
  roles:
    - k3s-ansible/roles/k3s/server-join
