---
- name: Configurar estaciones de trabajo
  hosts: workstations
  # vars:
  #   dotfiles_repo: "https://github.com/grilix/dotfiles.git"
  #   dotfiles_dest_path: "{{ ansible_env.HOME }}/Source/dotfiles"
  tasks:
    - name: paquetes instalados
      become: true
      apt:
        pkg:
          - htop
  roles:
    #- docker
    - workstation
