---
- name: paquetes instalados
  become: true
  apt:
    pkg:
      - acl
      - nfs-kernel-server

- name: directorio existe
  become: true
  file:
    path: "{{ nfs_server_path }}"
    state: directory

- name: directorio montado
  become: true
  mount:
    path: '{{ nfs_server_path }}'
    src: "UUID={{ nfs_filesystem_uuid }}"
    state: mounted
    opts: doatime,norelatime,nodiratime,nodev,noexec
    fstype: ext4

- name: directorio montado tiene los permisos correctos
  become: true
  file:
    path: "{{ nfs_server_path }}"
    mode: 0774
    owner: nobody
    group: nogroup
    state: directory

- name: ACL | configuración de usuario
  become: true
  acl:
    state: present
    path: '{{ nfs_server_path }}'
    default: true
    etype: user
    permissions: "rwX"

- name: ACL | configuración de grupo
  become: true
  acl:
    state: present
    path: '{{ nfs_server_path }}'
    default: true
    etype: group
    permissions: "rwX"

- name: ACL | configuración para otros
  become: true
  acl:
    state: present
    path: '{{ nfs_server_path }}'
    default: true
    etype: other
    permissions: "rx"

- name: directorio exportado
  become: true
  lineinfile:
    path: '/etc/exports'
    line: "{{ nfs_server_path }} {{ nfs_export_settings }}"
    regexp: "^{{ nfs_server_path }} "
  notify:
    - servidor nfs reiniciado
